# -*- coding: utf-8 -*-
"""Shohjahon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ShohjahonbekInomjonov/loyiha1/blob/main/Shohjahon.ipynb
"""

import numpy as np
#1.massiv yaratish
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([1,2,3,4,5,6])

#2.matematik operatsiyalar
sum_array = np.sum(array_1d)
mean_array = np.mean(array_1d)
product_array = np.prod(array_1d)


print("1D Massiv : ", array_1d)
print("2D Massiv :\n", array_2d)
print("Massivlar yig'indisi:  ", sum_array)
print("O'rtacha : ", mean_array)
print("Ko'paytma : ", product_array)

import pandas as pd
# 1. dataframe yaratish
data={
    'ism': ['Ali', 'Vali', 'Sardor'],
    'yoshi' : [25,30,22],
    'shahar' : ['Toshkent', 'Samarqand', 'Buxoro']
}
df = pd.DataFrame(data)

# 2.Ma'lumotlarni ko'rish
print(df)

#3.Filtrlash
young_people = df[df['yoshi']<30]
print("30 yoshdan kichiklar:\n", young_people)

#4.O'zgartirish
df['yoshi'] += 1 #har bir shaxsning yoshini birga oshirish
print("yangilangan dataframe:\n",df)
#5.